version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "express"  # Newer versions of sphinx-jsonschema have compatibility issues
