version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    python-dependencies:
      patterns:
        - "*"
    documentation-dependencies:
      patterns:
        - "sphinx*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    actions-dependencies:
      patterns:
        - "*"