name: Deploy to production

on:
  release:
    types: [published]

jobs:
  update_code_production:
    name: Update code on production
    runs-on: self-hosted
    
    steps:
      - name: Update code from GitHub
        run: |
            TAG=$(git describe --tags --abbrev=0)
            echo "Updating to hash $TAG"
            cd /ihome/crc/wrappers
            git fetch
            git checkout tags/$TAG
