name: Deploy new code

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  fetch_code_on_production:
    name: Fetch new code on production
    runs-on: self-hosted
    
    steps:
      - name: Checkout source
        run: |
            GITHASH=$(git rev-parse --short "$GITHUB_SHA")
            echo "Updateing to hash $GITHASH"
            cd /ihome/crc/wrappers
            git fetch
            git checkout $GITHASH
