name: Deploy to production

on:
  release:
    types: [published]

jobs:
  update_code_production:
    name: Update code on production
    runs-on: self-hosted
    
    steps:
      - name: Update code from GitHub
        run: |
            GITHASH=$(git rev-parse --short "$GITHUB_SHA")
            echo "Updateing to hash $GITHASH"
            cd /ihome/crc/wrappers
            git fetch
            git checkout $GITHASH
